### ISSUE TITLE
I would like to re-use Primes.Factorization for polynomials

### ISSUE THREAD

**Issue by jmichel7** [JuliaMath/Primes.jl#126]
I have written code for factoring a univariate polynomial over a finite field, and over the integers (modules `Fact` and `FFfac` in my package `Gapjm`). I thought it would be convenient to use `Primes.Factorization`  to store these factorizations. However, I cannot since it is written in several places `T<:Integer`.

Are these annotations really useful? It seems to me they are not...

**Comment by oscardssmith** [comment]
I think this should be doable. I don't believe we are using the assumption of integer type anywhere.

**Comment by jmichel7** [comment]
Excellent! I wait for this... Unless you want me to make a pr?

**Comment by oscardssmith** [comment]
can you make the PR? I'll merge.

**Comment by jmichel7** [comment]
Thank you for merging! Are you going to do a release? It would be good to have this and also the function `divisors` ...

**Comment by oscardssmith** [comment]
I'm going to give myself a few days (mainly because I might want to get https://github.com/JuliaMath/Primes.jl/pull/120 in also). that said if I haven't made a release in a week or so, feel free to bump this.

as for divisors, I'm probably not going to write the code myself, but if there was a PR for it I probably would merge (even though I kind of think the multiplicative functions might belong in a separate package)

**Comment by jmichel7** [comment]
But the code for `divisors` is already there in `master`!

**Comment by jmichel7** [comment]
"if I haven't made a release in a week or so, feel free to bump this."

BUMP!

**Comment by oscardssmith** [comment]
version tagged. sorry for the wait.

**Comment by fingolfin** [comment]
Can this be closed?
