### ISSUE TITLE
nextprime(p) == p

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaMath/Primes.jl#48]
for p a prime, `nextprime(p) == p`

this should be changed so that for i>0 an integer  `nextprime(i) > i`

thanks to [leiteiro, here](https://discourse.julialang.org/t/the-prevprime-and-nextprime-functions/4163) for noticing

**Comment by ararslan** [comment]
The current behavior was chosen explicitly, though it's indeed been pointed out that it's inconsistent with the behavior of a few other systems. Since this functionality is so new, we could probably just change it and tag, though I have no strong opinions on what the right approach is.

**Comment by JeffreySarnoff** [comment]
p is a strictly positive Integer 
P is a strictly positive Integer that is prime
 
In the past, I have used `isprime(p)` with the advancing form of `nextprime(p)` to emulate the nonadvancing form of `nextprime(P)`.  That need arises infrequently and precludes counterintuitive nomenclature.

**Comment by rfourquet** [comment]
I feel the way it is makes some sense: 
1) if I know that `P` is a prime (e.g. I'm iterating over the primes), then to get the nextprime just use `nextprime(P+1)`
2) if I don't know wether `p` is prime or not, e.g I chose `p` randomly, then I would guess that in most of the use cases, `nextprime(p)` returning `p` if `p` is prime would be ok. Otherwise, it's again enough to call `nextprime(p+1)`.

Note that it's not needed to call `isprime(p)` together with the nonadvancing form of `nextprime(P)` to emulate the advancing form of `nextprime(P)`, only a simple addition: `nextprime(P+1)`, so this seems overall like a win to me.

I won't pretend that this current API is absolutely better, but as @stevengj noted on the discourse thread, one reason I chose it that way is to be consistent with `nextpow` from base; and also, it's this way in the world-class number theory CAS system PARI.

**Comment by JeffreySarnoff** [comment]
PARI is PARI and was best in class before it was fashionable.  A few years ago, there was a cogent effort to change `nextpow` in this same way, for the same reason.  With the benefit of hindsight and imperfect recollection of the debate, I remain in that camp.  Nonetheless, the perspective that held sway then is the perspective that holds sway on this now.  There is no more access to this road, as being contrary to Base is baseless.
